apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-mongo-ns
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask-mongo-ns
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3Lw==  # mongodb://mongo:27017/
